DROP DATABASE VEGABURGUER;
CREATE DATABASE IF NOT EXISTS VEGABURGUER;
USE VEGABURGUER;

CREATE TABLE CATEGORIA (
nombre VARCHAR(255) NOT NULL,
id INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE PRODUCTO (
nombre VARCHAR(255) NOT NULL,
precio DOUBLE NOT NULL,
idCategoria INT NOT NULL,
id INT AUTO_INCREMENT PRIMARY KEY,
CONSTRAINT fk_id_categoria FOREIGN KEY (idCategoria)
REFERENCES CATEGORIA(id)
ON DELETE CASCADE
);

CREATE TABLE PEDIDO (
nombre VARCHAR(255) NOT NULL,
id INT AUTO_INCREMENT PRIMARY KEY,
fecha DATE DEFAULT (CURRENT_DATE)
);

CREATE TABLE LINEAPEDIDO (
id INT AUTO_INCREMENT PRIMARY KEY,
idPedido INT NOT NULL,
idProducto INT NOT NULL,
precio DOUBLE NOT NULL,
cantidad INT NOT NULL,
CONSTRAINT fk_id_pedido FOREIGN KEY (idPedido)
REFERENCES PEDIDO(id)
ON DELETE CASCADE,
CONSTRAINT fk_id_producto FOREIGN KEY (idProducto)
REFERENCES PRODUCTO(id)
ON DELETE CASCADE
);


CREATE TABLE DEPENDIENTE (
nombre VARCHAR(255) NOT NULL,
contraseña VARCHAR(255) NOT NULL,
imagen_path VARCHAR(255),
activo BOOLEAN,
is_admin BOOLEAN
);
