DROP DATABASE VEGABURGUER;
CREATE DATABASE IF NOT EXISTS VEGABURGUER;
USE VEGABURGUER;

CREATE TABLE CATEGORIA (
    id VARCHAR(50) PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    image_path VARCHAR(255),
    enabled BOOLEAN
);

CREATE TABLE PRODUCTO (
    id VARCHAR(50) PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    precio DOUBLE NOT NULL,
    idCategoria VARCHAR(50) NOT NULL,
    image_path VARCHAR(255),
    enabled BOOLEAN,
    CONSTRAINT fk_id_categoria FOREIGN KEY (idCategoria)
        REFERENCES CATEGORIA(id)
        ON DELETE CASCADE
);

CREATE TABLE PEDIDO (
    id VARCHAR(50) PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    estado VARCHAR(50) DEFAULT 'PENDIENTE'
);

CREATE TABLE LINEAPEDIDO (
    id VARCHAR(50) PRIMARY KEY,
    idPedido VARCHAR(50) NOT NULL,
    idProducto VARCHAR(50) NOT NULL,
    precio DOUBLE NOT NULL,
    cantidad INT NOT NULL,
    CONSTRAINT fk_id_pedido FOREIGN KEY (idPedido)
        REFERENCES PEDIDO(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_id_producto FOREIGN KEY (idProducto)
        REFERENCES PRODUCTO(id)
        ON DELETE CASCADE
);

CREATE TABLE DEPENDIENTE (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    image_path VARCHAR(255),
    enabled BOOLEAN,
    is_admin BOOLEAN
);
